### ISSUE TITLE
Thanks for developing this package

### ISSUE THREAD

**Issue by carlosyanez** [HughParsonage/Census2021.DataPack#2]
Hi @HughParsonage ,

Thanks for creating this package.
I just wanted to check the status of the package and data, i..e is still WIP? - I'm collecting data for my Master's project, so I need to double check :) 
(If that's not the case and there is pending work, I'm more than happy to assist).

Kind Regards,
Carlos

**Comment by HughParsonage** [comment]
I don't have any pending work. Is there anything you think that should be included?

**Comment by carlosyanez** [comment]
Sorry, for the delay in my response.
Thanks for confirming -  I don't have any concerns about the content :) . I've also noticed you have collated data from previous Census.

As part of my project, I will be writing code to look at Census data across time (for electorates), so I was thinking of packaging in a similar way I'm doing with https://github.com/carlosyanez/auspol . Would be OK if I build on your repositories, since you have already collated the data (and made it readable by humans). Of course, I'll credit you as key contributor .

Thanks,
Carlos
